### ISSUE TITLE
MMHC too long to run 

### ISSUE THREAD

**Issue by yeqiaoling** [vspinu/bnlearn#1]
Hi,

 I'm using MMHC with default phases, MMPC and PC, but in some data sets, MMHC took too much time. Could I specify max iteration some where? On codes here, I see an argument of "max.iter", but it is not available on the function/library that I downloaded from CRAN. Please help. Thanks!

Best,
Qiaoling

**Comment by yeqiaoling** [comment]
I found the augument "max.iter" for PC and encoded it in MMHC, but it's still slow. Could you give me some hints/guidance to check how to make it work? Thanks!

**Comment by vspinu** [comment]
This is a clone of the bnlearn package. I am not the author nor I work with bnlearn any longer. Pls contact the author.
